# Generated by Django 4.2.15 on 2024-09-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='blog/none.jpg', null=True, upload_to='blog/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
