# Generated by Django 4.2.15 on 2024-09-14 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта клиента')),
                ('first_name', models.CharField(blank=True, default='Не указано', max_length=100, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='Не указано', max_length=100, null=True, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, default='Не указано', max_length=100, null=True, verbose_name='Отчество')),
                ('comment', models.CharField(blank=True, default='Не указано', max_length=50, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt', models.DateTimeField(auto_now_add=True, verbose_name='Последняя попытка')),
                ('status_attempt', models.CharField(choices=[('Успешно', 'Успешно'), ('Ошибка', 'Ошибка')], max_length=150, verbose_name='Статус попытки')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера')),
            ],
            options={
                'verbose_name': 'Лог рассылки',
                'verbose_name_plural': 'Логи рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название рассылки')),
                ('start_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Начало рассылки')),
                ('stop_at', models.DateTimeField(default=datetime.datetime(2024, 9, 15, 16, 37, 5, 161134), verbose_name='Конец рассылки')),
                ('next_send_time', models.DateTimeField(blank=True, null=True, verbose_name='Время следующей отправки')),
                ('periodicity', models.CharField(choices=[('EVERY_DAY', 'Каждый день'), ('EVERY_WEEK', 'Каждую неделю'), ('EVERY_MONTH', 'каждый месяц')], default='EVERY_DAY', max_length=100, verbose_name='Периодичность рассылки')),
                ('status', models.CharField(choices=[('Создана', 'Создана'), ('В работе', 'Работает'), ('Завершена', 'Завершена')], default='Создана', max_length=100, verbose_name='Статус рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['id'],
                'permissions': [('Disabled_mailing', 'Disabled mailing'), ('view_all_list', 'view all list')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=150, verbose_name='Тема письма')),
                ('body', models.TextField(verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
