# Generated by Django 4.2.15 on 2024-09-01 14:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта клиента')),
                ('first_name', models.CharField(blank=True, default='Не указано', max_length=100, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='Не указано', max_length=100, null=True, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, default='Не указано', max_length=100, null=True, verbose_name='Отчество')),
                ('comment', models.CharField(blank=True, default='Не указано', max_length=50, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=150, verbose_name='Тема письма')),
                ('body', models.TextField(verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название рассылки')),
                ('start_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Начало рассылки')),
                ('stop_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец рассылки')),
                ('periodicity', models.CharField(choices=[('EVERY_DAY', 'Каждый день'), ('EVERY_WEEK', 'Каждую неделю'), ('EVERY_MONTH', 'каждый месяц')], default='EVERY_DAY', max_length=100, verbose_name='Периодичность рассылки')),
                ('status', models.CharField(choices=[('CREATED', 'Создана'), ('WORKS', 'Работает'), ('FINISH', 'Завершена')], default='CREATED', max_length=100, verbose_name='Статус рассылки')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_settings', to='mailings.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt', models.DateTimeField(auto_now_add=True, verbose_name='Последняя попытка')),
                ('status_attempt', models.CharField(choices=[('SUCCESS', 'Успешно'), ('ERROR', 'Ошибка')], max_length=150, verbose_name='Статус попытки')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера')),
                ('mailing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_log', to='mailings.mailingsettings', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Лог рассылки',
                'verbose_name_plural': 'Логи рассылки',
            },
        ),
    ]
