# Generated by Django 4.2.15 on 2024-09-01 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='client',
            field=models.ManyToManyField(blank=True, null=True, related_name='mailing_settings', to='mailings.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='creator',
            field=models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
    ]
