# Generated by Django 4.2.15 on 2024-09-04 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_mailingsettings_client_mailingsettings_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='stop_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 5, 23, 44, 53, 498598), verbose_name='Конец рассылки'),
        ),
    ]
