# Generated by Django 4.2.15 on 2024-09-08 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_client_creator_mailinglog_creator_message_creator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'ordering': ['id'], 'permissions': [('Disabled_mailing', 'Disabled mailing'), ('view_all_list', 'view all list')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='stop_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 20, 54, 15, 347181), verbose_name='Конец рассылки'),
        ),
    ]
