# Generated by Django 4.2.15 on 2024-09-04 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_alter_mailingsettings_stop_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='next_send_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время следующей отправки'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='stop_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 0, 7, 22, 989666), verbose_name='Конец рассылки'),
        ),
    ]
