# Generated by Django 4.2.15 on 2024-09-08 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0004_alter_mailingsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='stop_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 21, 32, 8, 153351), verbose_name='Конец рассылки'),
        ),
    ]
