# Generated by Django 4.2.15 on 2024-09-04 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_alter_mailingsettings_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='stop_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 0, 7, 46, 15396), verbose_name='Конец рассылки'),
        ),
    ]
