# Generated by Django 4.2.15 on 2024-09-05 22:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0006_alter_mailingsettings_stop_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_log', to='mailings.mailingsettings', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='status_attempt',
            field=models.CharField(choices=[('Успешно', 'Успешно'), ('Ошибка', 'Ошибка')], max_length=150, verbose_name='Статус попытки'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('В работе', 'Работает'), ('Завершена', 'Завершена')], default='Создана', max_length=100, verbose_name='Статус рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='stop_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 1, 5, 46, 600682), verbose_name='Конец рассылки'),
        ),
    ]
